name: tests-auth

on:
  pull_request:
    paths:
      - 'server/auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd server/auth && npm i && npm run test:ci

