name: tests-orders

on:
  pull_request:
    paths:
      - 'server/orders/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        working-directory: server/orders
        run: npm install

      - name: Run tests
        working-directory: server/orders
        run: npm run test:ci